image: node:latest

stages:
  - build
  - deploy


install:
  stage: build
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build
  artifacts:
    paths:
      - dist/
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: push

deploy_master:
  stage: deploy
  script:
    - echo "Deploy a review app"
    - npm run build -- --base-href=/$CI_PROJECT_NAME/master/
    - mkdir -p /deployed/$CI_PROJECT_NAME
    - rm -rf /deployed/$CI_PROJECT_NAME/master
    - cp -r dist/ /deployed/$CI_PROJECT_NAME/master
  environment:
    name: master
    url: http://frparrffgitlab.corp.capgemini.com:9080/$CI_PROJECT_NAME/master/index.html
  only:
    - master
  dependencies:
    - install
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull

deploy_master_doc:
  stage: deploy
  script:
    - echo "Deploy a review app doc"
    - npm run doc
    - mkdir -p /deployed/$CI_PROJECT_NAME
    - rm -rf /deployed/$CI_PROJECT_NAME/master_doc
    - cp -r documentation/ /deployed/$CI_PROJECT_NAME/master_doc
  environment:
    name: master_doc
    url: http://frparrffgitlab.corp.capgemini.com:9080/$CI_PROJECT_NAME/master_doc/index.html
  only:
    - master
  dependencies:
    - install
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull

