image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - npm install

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
  policy: pull

build-app:
  stage: build
  script:
    - apt-get install zip
    - npm run build:app --base-href=/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/app/
    - zip -r $CI_PROJECT_NAME_$CI_COMMIT_REF_SLUG.war dist/app
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: push
  artifacts:
    paths:
      - dist/app/
      - $CI_PROJECT_NAME_$CI_COMMIT_REF_SLUG.war

build-lib:
  stage: build
  script:
    - npm run build:lib
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - dist/lib/

doc:
  stage: test
  script:
    - echo "Génération de la documentation"
    - npm run doc
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - documentation/

test:
  stage: test
  image: frparrffgitlab.corp.capgemini.com:4567/infrastructure/dockerfiles/socle-npm-chrome
  script:
    - echo "Tests unitaires"
    - npm run ng test --watch=false --single-run --code-coverage --browsers=Chromium_CI
  allow_failure: true
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - coverage/
      - test-report.html

e2e:
  stage: test
  image: frparrffgitlab.corp.capgemini.com:4567/infrastructure/dockerfiles/socle-npm-chrome
  script:
    - echo "Tests end-to-end"
    - npm run e2e
  allow_failure: true
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull

deploy-app:
  stage: deploy
  script:
    - echo "Deploy a review app"
    - rm -rf /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/app
    - mkdir -p /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/app
    - cp -r dist/app/ /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/app

  environment:
    name: $CI_COMMIT_REF_SLUG-app
    url: http://frparrffgitlab.corp.capgemini.com:9080/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/app/
  dependencies:
    - build-app



deploy-coverage:
  stage: deploy
  script:
    - echo "Deploy test coverage"
    - rm -rf /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/cov
    - mkdir -p /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/cov
 #   - cp -r coverage/ /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/cov
#   - cp test-report.html /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/cov/test-report.html
  environment:
    name: $CI_COMMIT_REF_SLUG-cov
    url: http://frparrffgitlab.corp.capgemini.com:9080/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/cov/
  dependencies:
    - test



deploy-doc:
  stage: deploy
  script:
    - echo "Deploy documentation"
    - rm -rf /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/doc
    - mkdir -p /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/doc
    - cp -r documentation/ /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/doc

  environment:
    name: $CI_COMMIT_REF_SLUG-doc
    url: http://frparrffgitlab.corp.capgemini.com:9080/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/doc/
  dependencies:
    - doc
