image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - npm install

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
  policy: pull

build-app:
  stage: build
  script:
    - npm run build
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: push
  artifacts:
    paths:
      - dist/app/

build-lib:
  stage: build
  script:
    - npm run build:lib
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - dist/lib/

doc:
  stage: test
  script:
    - echo "Génération de la documentation"
    - npm run doc
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - documentation/

test:
  stage: test
  script:
    - echo "Tests unitaires"
#   - npm run test:coverage
  allow_failure: true
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - coverage/
      - test-report.html

e2e:
  stage: test
  script:
    - echo "Tests end-to-end"
#    - npm run e2e
  allow_failure: true
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull

deploy:
  stage: deploy
  script:
    - echo "Deploy a review app"
    - mkdir -p /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
    - cp -r dist/lib/ /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/app
    - cp -r dist/app/ /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/lib
    - cp -r documentation/ /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/documentation
    - cp -r coverage/ /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/coverage
    - cp test-report.html /deployed/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/test-report.html

  environment:
    name: $CI_COMMIT_REF_NAME
    url: http://frparrffgitlab.corp.capgemini.com:9080/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/
  dependencies:
    - build-app
    - build-lib
    - test
    - doc
  cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
    policy: pull

