sudo: required
dist: trusty
language: node_js

node_js:
   - node # will use latest node
sudo: required
addons:
  chrome: stable
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script: # commands to run before the build step
  - npm install -g angular-cli
  - npm install -g karma
  - npm install

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

cache:
  directories:
    - "node_modules"

stages:
  - build
  - test
  - e2e

build:
  - ng build --prod --base-href=cli-with-esri/

test:
  - ng test --watch=false --single-run --no-progress --code-coverage --browser=Chrome_CI

e2e:
  - ng e2e --no-progress

deploy:
  local-dir: dist/app
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

