language: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - npm install

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   

cache:
  directories:
    - "node_modules"

stages:
  - build
  - test

build:
  - ng build

test:
  - ng test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

